### PR TITLE
Rename cmake_common_scripts references to ros_industrial_cmake_boilerplate

### PR DESCRIPTION
**Pull request by schornakj**
- The `cmake_common_scripts` has been renamed to `ros_industrial_cmake_boilerplate`, so we need to rename our uses of the package name here.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@schornakj Do you know of any other packages which might be using cmake_common_scripts? I went through last night and updated several and missed this one, so not sure if there are any others that need updating.

**Comment by schornakj** [comment]
@Levi-Armstrong `yak_ros`, and `yak_ros2` are also affected, though I think mostly as a consequence of Yak's dependency on `cmake_common_scripts`. I'll push up fixes for those ones too.

**Comment by schornakj** [comment]
@Levi-Armstrong This is ready for review once CI finishes.

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by schornakj** [comment]
@Levi-Armstrong `yak_ros` and `yak_ros2` both build successfully using these changes without requiring additional modifications.

**Pull request merged**
