### PR TITLE
Fix incorrect handling of -f-prefixed options in PCL 1.8.X

### LINKED ISSUE #51: <command-line>:0:1: error: macro names must be identifiers
**platform: Jetson Xavier NX, ubuntu18.04**
It seems like [#9](https://github.com/ros-industrial/yak/issues/9). But #9 had been resolved.

Screenshot from 2020-08-19 16-03-27

### PR DESCRIPTION
**Pull request by schornakj**
Fixes #51.

- Modify the `target_add_options_and_definitions` macro so it adds options prefixed with `-f` to the target through `target_compile_options`.
- Use `separate_arguments` to split the list of options and definitions into individual elements. Convert the list to be space-delimited before it is passed to `separate_arguments`.

### CODE REVIEW

**Comment by schornakj** [comment]
@Levi-Armstrong Do you have time to take a look at this?

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by Levi-Armstrong** [comment]
This might be a useful macro to add to cmake_common_script; what do you think?

**Comment by schornakj** [comment]
> This might be a useful macro to add to cmake_common_script; what do you think?

It probably would be, since it started out as a script from Tesseract originally. We'd have to be a little careful to test all the downstream dependent packages against any changes to `cmake_common_scripts` to make sure we don't accidentally break anything.

**Comment by schornakj** [comment]
I think I might need a different strategy for splitting options, since based on the [GCC options summary](https://gcc.gnu.org/onlinedocs/gcc/Option-Summary.html) there are a few options that have `-f` and `-m` in the middle of the string rather than strictly as a prefix (for example, `-freorder-functions` and `-fassociative-math`).

**Comment by Levi-Armstrong** [comment]
What about switching the logic that it matches on -D for compiler definitions and everything else is an options?

**Comment by Levi-Armstrong** [comment]
It looks like compiler definitions must begin with`-D or /D` shown [here](https://cmake.org/cmake/help/v3.0/command/add_definitions.html).

**Comment by drchrislewis** [comment]
@schornakj @Levi-Armstrong I don't have the privileges to merge this, but I think it is ready to merge. Please do so.

**Comment by Levi-Armstrong** [comment]
@schornakj you good with merging this?

**Comment by schornakj** [comment]
@drchrislewis @Levi-Armstrong I need to finish implementing this change that Levi suggested, since otherwise it won't correctly handle some compile options:

> What about switching the logic that it matches on -D for compiler definitions and everything else is an options?

This should just take a short time to finish.

**Comment by schornakj** [comment]
On second thought, I'm going to leave this as-is for now. We can revisit later if there are additional issues to fix.

This change is specifically a fix for PCL 1.8, which doesn't do a good job of handling the contents of `PCL_DEFINITIONS`. On PCL 1.9 and later we can use the regular `target_compile_options` function on `PCL_COMPILE_OPTIONS`. I don't think that PCL adds any of the problematic option flags I mentioned earlier to `PCL_DEFINITIONS`, so it's probably unnecessary to come up with a really robust way to handle splitting this list.

**Pull request merged**
